// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env from project root (so local builds work). On Netlify, set DATABASE_URL in Site env vars.
config({ path: path.resolve(process.cwd(), ".env") });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] as string,
  },
});
